### ISSUE TITLE
Deal with GHA deprecation warnings

### ISSUE THREAD

**Issue by DMRobertson** [matrix-org/netlify-pr-preview#9]
See https://github.com/matrix-org/synapse/issues/14203 for more context.

The warnings I have in mind are e.g. https://github.com/matrix-org/synapse/actions/runs/4936859583

There are two categories of warnings. First:

> Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16:
> - actions/github-script@v5

That comes from matrix-org/pr-details-action@v1.1. The warning should be fixed by #5, which pulls in https://github.com/matrix-org/pr-details-action/pull/4.

- nwtgck/actions-netlify@f517512ae75beec8896aa7b027c1c72f01816200

Merging #8 should fix this, which pulls in https://github.com/nwtgck/actions-netlify/pull/847.

Second: 

> The `set-output` command is deprecated and will be disabled soon.

https://github.com/matrix-org/synapse/actions/runs/4936859583/jobs/8824910967#step:3:30 is probably the easiest way to see where these come from.

- https://github.com/matrix-org/netlify-pr-preview/pull/7 would cover the warnings about bobheadxi/deployments (see https://github.com/bobheadxi/deployments/issues/123 and https://github.com/bobheadxi/deployments/issues/124)
- the rest should be covered by #8.

I am happy to do this.

**Comment by DMRobertson** [comment]
> I am happy to do this.

I was going to PR the changes, but I think merging #5, #7, #8 should fix this. @t3chguy would it be possible to merge those and release a new version of this action? (If it's any easier, I'm happy to do so if you prefer and are willing to grant me write access to the repository.)

**Comment by t3chguy** [comment]
@DMRobertson https://github.com/matrix-org/netlify-pr-preview/releases/tag/v2

**Comment by DMRobertson** [comment]
Thank you!!
